import { writeFile } from "node:fs/promises";
import path from "node:path";
import { chromium } from "@playwright/test";

/**
 * Draws the app's icon files from the one mark the header already renders.
 *
 * The nav and the auth lockup render lucide's `Droplets` in `--brand`, and the
 * browser tab shows the same mark in the same colour — but it cannot share the
 * code. `src/app/icon.svg`, `favicon.ico` and `apple-icon.png` are static files
 * Next serves off the filesystem; they cannot import from `lucide-react` or
 * read a CSS custom property. So the path data and the colours are copied here,
 * and this script is what keeps the three of them saying the same thing.
 *
 * Run it by hand after changing the mark or `--brand`, and commit the output.
 * It is deliberately not part of `build`: the icons are committed binaries, and
 * a deploy has no business re-rasterising them.
 *
 *   pnpm exec tsx scripts/generate-icons.ts
 */

/**
 * Verbatim from `node_modules/lucide-react/dist/esm/icons/droplets.mjs`
 * (lucide-react 1.46.0), so a future upgrade has something to diff against.
 */
const DROPLETS = [
  "M7 16.3c2.2 0 4-1.83 4-4.05 0-1.16-.57-2.26-1.71-3.19S7.29 6.75 7 5.3c-.29 1.45-1.14 2.84-2.29 3.76S3 11.1 3 12.25c0 2.22 1.8 4.05 4 4.05z",
  "M12.56 6.6A10.97 10.97 0 0 0 14 3.02c.5 2.5 2 4.9 4 6.5s3 3.5 3 5.5a6.98 6.98 0 0 1-11.91 4.97",
];

/**
 * lucide draws at `stroke-width: 2` on a 24 viewBox, which lands on 1.3px once
 * the mark is 16px wide and smears into mush. The heavier stroke is the only
 * liberty taken with the glyph.
 */
const STROKE_WIDTH = 2.4;

/** sRGB equivalents of `--brand` in `src/app/globals.css`. Keep in step. */
const BRAND_LIGHT = "#378ADD";
const BRAND_DARK = "#85B7EB";

/**
 * A raster icon cannot carry a media query, so `favicon.ico` splits the
 * difference between the two and stays legible on either tab bar.
 */
const BRAND_FLAT = "#5EA0E4";

/** `--background` in `.dark` — the ground iOS composites the home screen icon on. */
const GROUND_DARK = "#0A0A0A";

/**
 * lucide's glyphs run to the edge of their box, which is right for an icon sat
 * in a line of text and cramped for a tile sat on a home screen next to Apple's
 * own. Two viewBox units of air on each side, for the apple-icon only — the
 * favicon wants every pixel it can get at 16px.
 */
const APPLE_INSET = 2;

/** The sizes Windows and browsers actually pull out of an .ico. */
const ICO_SIZES = [16, 32, 48];
const APPLE_SIZE = 180;

function markup(stroke: string, size: number, background?: string, inset = 0) {
  const box = 24 + inset * 2;
  const paths = DROPLETS.map((d) => `<path d="${d}" />`).join("");
  const ground = background
    ? `<rect x="${-inset}" y="${-inset}" width="${box}" height="${box}" ` +
      `fill="${background}" stroke="none" />`
    : "";
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" ` +
    `viewBox="${-inset} ${-inset} ${box} ${box}" ` +
    `width="${size}" height="${size}" fill="none" stroke="${stroke}" ` +
    `stroke-width="${STROKE_WIDTH}" stroke-linecap="round" ` +
    `stroke-linejoin="round">${ground}${paths}</svg>`
  );
}

/**
 * The served vector, and the only one of the three that can follow the reader:
 * browsers apply `prefers-color-scheme` inside a favicon, and tab chrome tracks
 * the OS rather than this app's own Light/Dark/System toggle.
 *
 * The `<title>` stays English. A static asset is served with no request behind
 * it and therefore no locale to resolve — the same gap that makes the digest
 * read `user_settings.locale` instead of the cookie — and it is the app's name
 * rather than prose.
 */
function iconSvg() {
  const paths = DROPLETS.map((d) => `  <path d="${d}" />`).join("\n");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="${BRAND_LIGHT}" stroke-width="${STROKE_WIDTH}" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by scripts/generate-icons.ts — do not edit by hand. -->
  <title>My Filter</title>
  <style>
    @media (prefers-color-scheme: dark) {
      path { stroke: ${BRAND_DARK}; }
    }
  </style>
${paths}
</svg>
`;
}

/**
 * Rasterises through the Chromium that Playwright already installs for the e2e
 * suite, rather than pulling in sharp or a wasm renderer for three files.
 */
async function rasterise(svgs: string[]) {
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    const out: Buffer[] = [];
    for (const svg of svgs) {
      // Inline, not an <img> pointing at a file: or data: URI. Chromium blocks
      // those as subresources of a setContent document and does it silently —
      // the screenshot still succeeds, and what it captures is the broken-image
      // placeholder rather than the mark.
      await page.setContent(`<body style="margin:0">${svg}</body>`);
      // An element capture, not a page one: Chromium refuses to screenshot a
      // viewport as small as 16x16, and an element is 1:1 with its CSS size
      // however big the page around it happens to be.
      out.push(await page.locator("svg").screenshot({ omitBackground: true }));
    }
    return out;
  } finally {
    await browser.close();
  }
}

/**
 * An .ico is a six-byte header, a sixteen-byte directory entry per image and
 * then the payloads. PNG-in-ICO has been understood since Vista and by every
 * browser this app targets, so the entries point straight at the PNG bytes.
 */
function packIco(images: { png: Buffer; size: number }[]) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // 1 = icon
  header.writeUInt16LE(images.length, 4);

  const directory = Buffer.alloc(16 * images.length);
  let offset = header.length + directory.length;

  for (const [index, { png, size }] of images.entries()) {
    const at = index * 16;
    directory.writeUInt8(size === 256 ? 0 : size, at); // 0 means 256
    directory.writeUInt8(size === 256 ? 0 : size, at + 1);
    directory.writeUInt8(0, at + 2); // palette size, 0 for truecolour
    directory.writeUInt8(0, at + 3); // reserved
    directory.writeUInt16LE(1, at + 4); // colour planes
    directory.writeUInt16LE(32, at + 6); // bits per pixel
    directory.writeUInt32LE(png.length, at + 8);
    directory.writeUInt32LE(offset, at + 12);
    offset += png.length;
  }

  return Buffer.concat([header, directory, ...images.map((i) => i.png)]);
}

async function main() {
  const app = path.join(import.meta.dirname, "..", "src", "app");

  await writeFile(path.join(app, "icon.svg"), iconSvg());

  const rendered = await rasterise([
    ...ICO_SIZES.map((size) => markup(BRAND_FLAT, size)),
    // iOS composites a transparent home screen icon straight onto the
    // wallpaper, so this is the one place the mark gets a ground.
    markup(BRAND_DARK, APPLE_SIZE, GROUND_DARK, APPLE_INSET),
  ]);

  const apple = rendered.pop();
  if (!apple) throw new Error("no apple-icon was rendered");
  await writeFile(path.join(app, "apple-icon.png"), apple);

  await writeFile(
    path.join(app, "favicon.ico"),
    packIco(rendered.map((png, index) => ({ png, size: ICO_SIZES[index] }))),
  );

  console.log(
    `wrote icon.svg, favicon.ico (${ICO_SIZES.join(", ")}) and apple-icon.png (${APPLE_SIZE})`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
